# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Vivado/code/SME309-RISCV-tmpl2/vivado/top.xdc

# IP: ip/DRAM/DRAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DRAM || ORIG_REF_NAME==DRAM} -quiet] -quiet

# IP: ip/IROM/IROM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IROM || ORIG_REF_NAME==IROM} -quiet] -quiet

# XDC: ip/DRAM/DRAM_ooc.xdc

# XDC: ip/IROM/IROM_ooc.xdc
