# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Vivado/code/SME309-RISCV-tmpl2/vivado/vivado_proj.cache/wt [current_project]
set_property parent.project_path D:/Vivado/code/SME309-RISCV-tmpl2/vivado/vivado_proj.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Vivado/code/SME309-RISCV-tmpl2/vivado/vivado_proj.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/Vivado/code/SME309-RISCV-tmpl2/scripts/build/all_test.coe
add_files D:/Vivado/code/SME309-RISCV-tmpl2/scripts/build/all_test_case.coe
add_files D:/Vivado/code/SME309-RISCV-tmpl2/scripts/build/add_loop.coe
read_verilog -library xil_defaultlib {
  D:/Vivado/code/SME309-RISCV-tmpl2/vivado/vivado_proj.srcs/sources_1/new/Alu.v
  D:/Vivado/code/SME309-RISCV-tmpl2/rtl/cpu/CPU_TOP.v
  D:/Vivado/code/SME309-RISCV-tmpl2/vivado/vivado_proj.srcs/sources_1/new/Control.v
  D:/Vivado/code/SME309-RISCV-tmpl2/vivado/vivado_proj.srcs/sources_1/new/Decoder.v
  D:/Vivado/code/SME309-RISCV-tmpl2/vivado/vivado_proj.srcs/sources_1/new/Extend.v
  D:/Vivado/code/SME309-RISCV-tmpl2/vivado/vivado_proj.srcs/sources_1/new/Memdata.v
  D:/Vivado/code/SME309-RISCV-tmpl2/vivado/vivado_proj.srcs/sources_1/new/ProgramCounter.v
  D:/Vivado/code/SME309-RISCV-tmpl2/vivado/vivado_proj.srcs/sources_1/new/RegisterFile.v
  D:/Vivado/code/SME309-RISCV-tmpl2/rtl/benchmark.v
  D:/Vivado/code/SME309-RISCV-tmpl2/rtl/dram_driver.v
  D:/Vivado/code/SME309-RISCV-tmpl2/vivado/vivado_proj.srcs/sources_1/new/ex_me.v
  D:/Vivado/code/SME309-RISCV-tmpl2/vivado/vivado_proj.srcs/sources_1/new/forward_unit.v
  D:/Vivado/code/SME309-RISCV-tmpl2/vivado/vivado_proj.srcs/sources_1/new/hazard_detection_unit.v
  D:/Vivado/code/SME309-RISCV-tmpl2/vivado/vivado_proj.srcs/sources_1/new/id_ex.v
  D:/Vivado/code/SME309-RISCV-tmpl2/vivado/vivado_proj.srcs/sources_1/new/if_id.v
  D:/Vivado/code/SME309-RISCV-tmpl2/vivado/vivado_proj.srcs/sources_1/new/me_wb.v
  D:/Vivado/code/SME309-RISCV-tmpl2/rtl/seven_seg.v
  D:/Vivado/code/SME309-RISCV-tmpl2/vivado/top.v
}
read_ip -quiet D:/Vivado/code/SME309-RISCV-tmpl2/vivado/vivado_proj.srcs/sources_1/ip/DRAM/DRAM.xci
set_property used_in_implementation false [get_files -all d:/Vivado/code/SME309-RISCV-tmpl2/vivado/vivado_proj.srcs/sources_1/ip/DRAM/DRAM_ooc.xdc]

read_ip -quiet D:/Vivado/code/SME309-RISCV-tmpl2/vivado/vivado_proj.srcs/sources_1/ip/IROM/IROM.xci
set_property used_in_implementation false [get_files -all d:/Vivado/code/SME309-RISCV-tmpl2/vivado/vivado_proj.srcs/sources_1/ip/IROM/IROM_ooc.xdc]

read_ip -quiet D:/Vivado/code/SME309-RISCV-tmpl2/vivado/vivado_proj.srcs/sources_1/ip/pll/pll.xci
set_property used_in_implementation false [get_files -all d:/Vivado/code/SME309-RISCV-tmpl2/vivado/vivado_proj.srcs/sources_1/ip/pll/pll_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/code/SME309-RISCV-tmpl2/vivado/vivado_proj.srcs/sources_1/ip/pll/pll.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/code/SME309-RISCV-tmpl2/vivado/vivado_proj.srcs/sources_1/ip/pll/pll_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Vivado/code/SME309-RISCV-tmpl2/vivado/top.xdc
set_property used_in_implementation false [get_files D:/Vivado/code/SME309-RISCV-tmpl2/vivado/top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
