webtalk_init -webtalk_dir D:/Vivado/code/SME309-RISCV-tmpl2/vivado/vivado_proj.sim/sim_1/behav/xsim/xsim.dir/tb_Top_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jan  8 07:53:23 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6b34a940-2c45-4da0-9b6a-22f7b7b3cae8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3e6eff3e2d4a4c50a15ac3f36e4eed88" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "128" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 6800H with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3194 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "467508882 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "62.14_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "19804_KB" -context "xsim\\usage"
webtalk_transmit -clientid 697049876 -regid "" -xml D:/Vivado/code/SME309-RISCV-tmpl2/vivado/vivado_proj.sim/sim_1/behav/xsim/xsim.dir/tb_Top_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Vivado/code/SME309-RISCV-tmpl2/vivado/vivado_proj.sim/sim_1/behav/xsim/xsim.dir/tb_Top_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Vivado/code/SME309-RISCV-tmpl2/vivado/vivado_proj.sim/sim_1/behav/xsim/xsim.dir/tb_Top_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
